Blog section design
front-end-by-rimantas/19-grupe-portfolio-new-per pull request #95
Opened 2020-12-12 20:22 UTC by VaidaEG

Dizainas be responsive.

2020-12-12 21:31 UTC, LaimonasMas approved these changes, later dismissed
atrodo ok 👍

2020-12-12 22:42 UTC, gvisis requested changes
💭

2020-12-12 22:42 UTC, gvisis commented on css/components/blog.css
> +.row.blog {
not sure ka sitas daro? Atrodo, kad net isstumia viska labiau i sonus, uz grido ribu

2020-12-12 22:42 UTC, gvisis commented on css/components/blog.css
> +            .info-img > .info {
Is viso sito realiai tereikia: 
```
    display: inline-block;
    float: left;
    vertical-align: center;
    width: calc(100% - 50px);
    padding: 8px;
    text-transform: uppercase;
    color: #232323;
```
Nes  sekantis stylingas `.info > *` permus visus tuos teksto nustatymus.
Tiesiog biski dubliuojasi.

2020-12-14 09:08 UTC, VaidaEG commented
Pakoregavau. Ačiū.

2020-12-14 09:32 UTC, gvisis approved these changes

2020-12-14 10:05 UTC, beatarynkevic approved these changes
👍🏽

2020-12-14 10:06 UTC, merged